#cloud-config
users:
  - name: nagibin
    groups: sudo
    shell: /bin/bash
    sudo: 'ALL=(ALL) NOPASSWD:ALL'
    ssh-authorized-keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMXJT6mUnfIcyblH0p6JG9Clu7yd7WaosxE7kp3cQRh0 root@DESKTOP-00G1TMP
write_files:
  - path: /home/nagibin/.ssh/id_ed25519
    content: |
      -----BEGIN OPENSSH PRIVATE KEY-----
      b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
      QyNTUxOQAAACDFyU+plJ3yHMm5R9KeiRvQpbu8ne1mqLMRO5Kd3EEYdAAAAJhqQrW7akK1
      uwAAAAtzc2gtZWQyNTUxOQAAACDFyU+plJ3yHMm5R9KeiRvQpbu8ne1mqLMRO5Kd3EEYdA
      AAAEAKMxUzg2AuUT2rLgjZhr2a48G/lKjtIgFnttDrkJQez8XJT6mUnfIcyblH0p6JG9Cl
      u7yd7WaosxE7kp3cQRh0AAAAFHJvb3RAREVTS1RPUC0wMEcxVE1QAQ==
      -----END OPENSSH PRIVATE KEY-----
    permissions: '0600'
  - path: /home/nagibin/.ssh/id_ed25519.pub
    content: |
      ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMXJT6mUnfIcyblH0p6JG9Clu7yd7WaosxE7kp3cQRh0 root@DESKTOP-00G1TMP
    permissions: '0600'
  - path: /var/spool/cron/crontabs/root
    content: |
      * * * * * /bin/chown -R nagibin:nagibin /home/nagibin/
    permissions: '0600'
#runcmd:
#  - [crontab -l | { cat; echo "* * * * * /bin/chown -R nagibin:nagibin /home/nagibin/.ssh/id_ed25519*"; } | crontab -]
