apiVersion: apps/v1
kind: Deployment
metadata:
   name: webserver
   namespace: default
spec:
   replicas: 3
   selector:
      matchLabels:
         app.kubernetes.io/component: webserver
         app.kubernetes.io/name: webserver
         app.kubernetes.io/part-of: kwebserver
   template:
      metadata:
         labels:
            app.kubernetes.io/component: webserver
            app.kubernetes.io/name: webserver
            app.kubernetes.io/part-of: kwebserver
      spec:
         containers:
            - name: webserver
              image: ghcr.io/pnagibin/webserver:latest
              imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: public-webserver
  namespace: default
spec:
  type: NodePort
  selector:
    app.kubernetes.io/component: webserver
    app.kubernetes.io/name: webserver
    app.kubernetes.io/part-of: kwebserver
  ports:      
  - name: web
    port: 80
    protocol: TCP
    targetPort: web
    nodePort: 30010