apiVersion: apps/v1
kind: Deployment
metadata:
   name: webserver
   namespace: default
spec:
   replicas: 3
   selector:
      matchLabels:
         bb: web
   template:
      metadata:
         labels:
            bb: web
      spec:
         containers:
            - name: webserver
              image: ghcr.io/pnagibin/webserver:latest
              imagePullPolicy: IfNotPresent