apiVersion: apps/v1
kind: Deployment
metadata:
   name: webserver
   namespace: default
spec:
   replicas: 3
   selector:
      matchLabels:
         bb: web
   template:
      metadata:
         labels:
            bb: web
      spec:
         containers:
            - name: webserver
              image: ghcr.io/pnagibin/webserver:latest
              imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: public-webserver
  namespace: default
spec:
  type: NodePort
  selector:
    bb: web
  ports:      
  - name: web
    port: 80
    protocol: TCP
    targetPort: web
    nodePort: 30010