apiVersion: apps/v1
kind: Deployment
metadata:
   name: webserver
   namespace: default
   labels:
      app.kubernetes.io/name: webserver
spec:
   replicas: 3
   selector:
      matchLabels:
         app.kubernetes.io/name: webserver
   template:
      metadata:
         labels:
            app.kubernetes.io/name: webserver
      spec:
         containers:
            - name: webserver
              image: ghcr.io/pnagibin/webserver:latest
              imagePullPolicy: IfNotPresent