apiVersion: v1
kind: Service
metadata:
  name: public-grafana
spec:
  type: NodePort
  selector:
    app.kubernetes.io/component: grafana
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: kube-prometheus
  ports:      
  - name: http
    port: 3000
    protocol: TCP
    targetPort: http
    nodePort: 30007