apiVersion: v1
kind: Service
metadata:
  name: public-grafana
  namespace: monitoring
spec:
  type: NodePort
  selector:
    app.kubernetes.io/component: grafana
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: kube-prometheus
  ports:      
  - name: http
    port: 3000
    protocol: TCP
    targetPort: http
    nodePort: 30007

---
apiVersion: v1
kind: Service
metadata:
  name: public-prometheus-k8s
  namespace: monitoring
spec:
  type: NodePort
  selector:
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/instance: k8s
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: kube-prometheus
  ports:      
  - name: web
    port: 9090
    protocol: TCP
    targetPort: web
    nodePort: 30008

---
apiVersion: v1
kind: Service
metadata:
  name: public-alertmanager-main
  namespace: monitoring
spec:
  type: NodePort
  selector:
    app.kubernetes.io/component: alert-router
    app.kubernetes.io/instance: main
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/part-of: kube-prometheus
  ports:      
  - name: web
    port: 9093
    protocol: TCP
    targetPort: web
    nodePort: 30009

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: webserver
  name: public-webserver
  namespace: default
spec:
  ports:
  - nodePort: 30010
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app.kubernetes.io/name: webserver
  sessionAffinity: None
  type: NodePort