- hosts: 127.0.0.1
  connection: local
  become: no
  #gather_facts: false
  tasks:
    - name: Install GitHub self-hosted runner
      retries: 3
      delay: 10
      shell: |
        mkdir /home/nagibin/actions-runner && cd /home/nagibin/actions-runner
        curl -o actions-runner-linux-x64-2.315.0.tar.gz -L https://github.com/actions/runner/releases/download/v2.315.0/actions-runner-linux-x64-2.315.0.tar.gz
        tar xzf ./actions-runner-linux-x64-2.315.0.tar.gz
        ./config.sh --url https://github.com/pnagibin/diplom-docker --token ANXOTK6SSMLNDDAFCDFBWTDGEYV76
        sudo ./svc.sh install nagibin
        sudo ./svc.sh start