- hosts: kubernetes-masters
  become: yes
  tasks:
    - name: install Kubectl
      retries: 3
      delay: 10
      apt:
        name: kubectl
        state: present
        force: yes # allow downgrades
    - name: create an empty file for Kubeadm configuring
      retries: 3
      delay: 10
      copy:
        content: ""
        dest: /etc/kubernetes/kubeadm-config.yaml
        force: no

    - name: configuring the container runtime including its cgroup driver
      retries: 3
      delay: 10
      blockinfile:
        path: /etc/kubernetes/kubeadm-config.yaml
        block: |
             kind: ClusterConfiguration
             apiVersion: kubeadm.k8s.io/v1beta3
             networking:
               podSubnet: "10.244.0.0/16"
             ---
             kind: KubeletConfiguration
             apiVersion: kubelet.config.k8s.io/v1beta1
             runtimeRequestTimeout: "15m"
             cgroupDriver: "systemd"
             systemReserved:
               cpu: 100m
               memory: 350M
             kubeReserved:
               cpu: 100m
               memory: 50M
             enforceNodeAllocatable:
             - pods

    - name: initialize the cluster (this could take some time)
      retries: 3
      delay: 10
      shell: kubeadm init --config /etc/kubernetes/kubeadm-config.yaml >> cluster_initialized.log
      args:
        chdir: /home/nagibin
        creates: cluster_initialized.log

    - name: create .kube directory
      retries: 3
      delay: 10
      become: yes
      become_user: nagibin
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755

    - name: copy admin.conf to user's kube config
      retries: 3
      delay: 10
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/nagibin/.kube/config
        remote_src: yes
        owner: nagibin

    - name: install Pod network
      retries: 3
      delay: 10
      become: yes
      become_user: nagibin
      shell: kubectl apply -f https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml >> pod_network_setup.log
      args:
        chdir: $HOME
        creates: pod_network_setup.log