- hosts: kubernetes-masters
  #gather_facts: false
  tasks:
    - name: kubectl apply -f https://raw.githubusercontent.com/pnagibin/netology-diplom/master/kubernetes/deployment.yaml
      retries: 3
      delay: 20
      shell: kubectl apply -f https://raw.githubusercontent.com/pnagibin/netology-diplom/master/kubernetes/deployment.yaml